# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64"

  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.host_name = "devbox"
  config.vm.customize [
                      "modifyvm", :id, 
                      "--memory", "3072",
                      "--cpus",    "4"
                      ]

  config.vm.network :hostonly, "192.168.111.111"

  config.vm.share_folder "v-root", "/vagrant", ".." , :nfs => false

  # whithout this symlinks can't be created on the shared folder
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
    chef.log_level = ENV['CHEF_LOG'] || "info"

#    chef.add_recipe "proxy"
    chef.add_recipe "cookbook"
    chef.add_recipe "apt"
    chef.add_recipe "openssl"
    chef.add_recipe "apache2"
    chef.add_recipe "mysql"
    chef.add_recipe "mysql::server"
    chef.add_recipe "apache2::mod_rewrite"

    #specific config
    chef.json = {
    	:proxy => {
	    	:http_proxy => "http://proxy.priv.atos.fr:3128",
    	},
        :mysql => {
            :server_root_password => 'helloroot',
		    :server_repl_password  => 'helloroot',
    	    :server_debian_password  => 'helloroot',
            :bind_address => '0.0.0.0'
        }
    }
  end
end
