imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @MopaBootstrapSandboxBundle/Resources/config/themes.yml }
    - { resource: @UcsEventFlowAnalyserBundle/Resources/config/menu.yml }
    - { resource: @UcsEventFlowAnalyserBundle/Resources/config/navbar.yml }
    - { resource: @MopaBootstrapSandboxBundle/Resources/config/examples/example_menu.yml }
    - { resource: @MopaBootstrapSandboxBundle/Resources/config/examples/example_navbar.yml }

mopa_bootstrap:
    navbar: ~

liip_theme:
    themes: ['bootstrap', 'initializr']
    active_theme: 'bootstrap'

framework:
    #esi:             ~
    translator:       ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        sass:
            bin: %sass.bin%
            apply_to: "\.sass$"
        scss:
            bin: %scss.bin%
            apply_to: "\.scss$"
        compass:
            bin: %compass.bin%
            apply_to: "\.[scss|sass]$"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
    assets:
        bootstrap:
            inputs:
                - @MopaBootstrapBundle/Resources/public/less/mopabootstrapbundle.less
            filters:
                - lessphp

#        cssrewrite: ~
#        cssembed:
#            jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
#            apply_to: "\.css$|\.less$"
#        yui_css:
#            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
#            apply_to: "\.css$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Atos\Worldline\Fm\UserBundle\Entity\User

