imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @MopaBootstrapSandboxBundle/Resources/config/themes.yml }
    - { resource: @UcsEventFlowAnalyser/Resources/config/menu.yml }
    - { resource: @UcsEventFlowAnalyser/Resources/config/navbar.yml }
    - { resource: @UcsEventFlowAnalyser/Resources/config/upload.yml }
    - { resource: @JQueryFileUploadBundle/Resources/config/assetic.yml }
    - { resource: @MopaBootstrapSandboxBundle/Resources/config/examples/example_menu.yml }
    - { resource: @MopaBootstrapSandboxBundle/Resources/config/examples/example_navbar.yml }

mopa_bootstrap:
    navbar: ~

liip_theme:
    themes: ['bootstrap', 'initializr']
    active_theme: 'bootstrap'

framework:
    #esi:             ~
    translator:       ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          false
    use_controller: false
    write_to:         %kernel.root_dir%/../web
    #bundles: []
    filters:
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
    assets:
        bootstrap_css:
            inputs:
                - @MopaBootstrapBundle/Resources/bootstrap/less/bootstrap.less
            output: css/bootstrap.min.css
            filters:
                - lessphp
                - yui_css
        bootstrap_js:
            inputs:
                - @MopaBootstrapBundle/Resources/bootstrap/js/*.js
            output: js/bootstrap.min.js
            filters:
                - yui_js
        prettify:
            inputs:
                - @MopaBootstrapSandboxBundle/Resources/public/css/prettify.css
            output: css/prettify.min.css
            filters:
                - yui_css
        UcsEventFlowAnalyser_css:
            inputs:
                - @UcsEventFlowAnalyser/Resources/assets/compass/stylesheets/base.css
                - @UcsEventFlowAnalyser/Resources/assets/compass/stylesheets/jquery-ui-1.9.1.custom.min.css
            output: css/UcsEventFlowAnalyser.min.css
            filters:
                - yui_css
        all:
            inputs:
                - @bootstrap_css
                - @prettify
                - @UcsEventFlowAnalyser_css
            output: css/all.min.css
            filters:
                - yui_css
        bootstrap:
            inputs:
                - @UcsEventFlowAnalyser/Resources/assets/js/jquery-1.7.2.min.js
                - @UcsEventFlowAnalyser/Resources/assets/js/jquery-ui-1.8.22.min.js
                - @UcsEventFlowAnalyser/Resources/assets/js/underscore-min.js
                - @MopaBootstrapBundle/Resources/public/js/mopabootstrap-collection.js
                - @MopaBootstrapBundle/Resources/public/js/mopabootstrap-subnav.js
                - @JQueryFileUploadBundle/Resources/public/js/jquery/jquery.fileupload.js
            output: js/bootstrap.min.js
            filters:
                - yui_js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Atos\Worldline\Fm\UserBundle\Entity\User

services:
    cache:
        class: Doctrine\Common\Cache\ApcCache
