parameters:
  database_driver:   pdo_mysql
  database_host:     localhost
  database_port:     ~
  database_name:     symfony
  database_user:     root
  database_password: 

  mailer_transport:  smtp
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  locale:            fr
  secret:            AZD1RFZ4F

  assetic.filter.compass.images_dir: '%kernel.root_dir%/../web/images'
  assetic.filter.compass.http_path:  /images

  app.data_dir: %kernel.root_dir%/../web/uploads/data
  app.event_xsd: %kernel.root_dir%/config/eventflow.xsd
  
# Nav bar
  knp_menu.renderer.twig.template: MopaBootstrapBundle:Menu:menu.html.twig

# Uploader
  file_uploader.file_base_path: "%kernel.root_dir%/../web/uploads"
  file_uploader.web_base_path: "/uploads"
  file_uploader.allowed_extensions:
    # Mime types are just for documentation's sake. 
    # BlueImp filters by supplied extension. No checking of the
    # actual file contents is done. If your mime types are 
    # configured correctly in Apache the browser will have the
    # correct expectations for each file
    - zip #archive
    - xml #text/xml

  # Folder where originals are uploaded. This is the only folder populated for
  # uploads that are not images
  file_uploader.originals:
      folder: originals

  file_uploader.sizes:

