parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: userDB
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: a58bc8b22d02d66f32109c419a7a73846
    database_path: null
