parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            AZD1RFZ4F

    # Assetic
    ruby.bin: D:\utils\Ruby\Ruby193\bin\ruby.exe
    sass.bin: D:\utils\Ruby\Ruby193\bin\sass.bat
    scss.bin: D:\utils\Ruby\Ruby193\bin\scss.bat
    compass.bin: D:\utils\Ruby\Ruby193\bin\compass
    less.node.bin: D:\utils\nodejs\node.exe
    less.node.path: D:\utils\nodejs\node_modules\npm\node_modules

    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images

