imports:
    - { resource: 'services_dao.yml' }
services:
  app.parser:
    class: Atos\Worldline\Fm\Integration\Ucs\EventFlowAnalyser\Service\ParserService
    arguments: ['@logger']

  app.project:
    class: Atos\Worldline\Fm\Integration\Ucs\EventFlowAnalyser\Service\ProjectService
    arguments: ['@logger']
    calls:
        - [ setParserService, [ '@app.parser' ] ]
   