services:
  app.persist_visitor:
    class: Mylen\EventFlowAnalyser\Dao\Visitor\PersistVisitor
    arguments: ['@doctrine.orm.entity_manager', '@logger']

  app.remove_visitor:
    class: Mylen\EventFlowAnalyser\Dao\Visitor\RemoveVisitor
    arguments: ['@doctrine.orm.entity_manager', '@logger']

  app.event_dao:
    class: Mylen\EventFlowAnalyser\Dao\EventDao
    arguments: ['@doctrine.orm.entity_manager', '@logger']
    calls:
        - [ setPersistVisitor, [ '@app.persist_visitor' ] ]
        - [ setRemoveVisitor, [ '@app.remove_visitor' ] ]

  app.project_dao:
    class: Mylen\EventFlowAnalyser\Dao\ProjectDao
    arguments: ['@doctrine.orm.entity_manager', '@logger']
    calls:
        - [ setPersistVisitor, [ '@app.persist_visitor' ] ]
        - [ setRemoveVisitor, [ '@app.remove_visitor' ] ]
 