imports:
    - { resource: 'services_dao.yml' }
services:
  app.parser:
    class: Atos\Worldline\Fm\Integration\Ucs\EventFlowAnalyser\Service\ParserService
    arguments: ['@logger']
    scope: container

  app.project:
    class: Atos\Worldline\Fm\Integration\Ucs\EventFlowAnalyser\Service\ProjectService
    arguments: ['@logger']
    scope: container
    calls:
        - [ setParserService, [ '@app.parser' ] ]
        - [ setFileUploaderService, [ '@mylen.file_uploader' ] ]
        - [ setProjectDao, [ '@app.project_dao' ] ]
   
  app.event:
    class: Atos\Worldline\Fm\Integration\Ucs\EventFlowAnalyser\Service\EventService
    arguments: ['@logger']
    scope: container
    calls:
        - [ setProjectService, [ '@app.project' ] ]
        - [ setEventDao, [ '@app.event_dao' ] ]
      