imports:
    - { resource: 'services_dao.yml' }
services:

  generate_project_all_graph_command:
    class: Mylen\EventFlowAnalyser\Command\GenerateProjectAllGraphCommand
    calls:
        - [setContainer, ["@service_container"] ]

  app.parser:
    class: Mylen\EventFlowAnalyser\Service\ParserService
    arguments: ['@logger']
    scope: container
   
  app.event:
    class: Mylen\EventFlowAnalyser\Service\EventService
    arguments: ['@logger']
    scope: container
    calls:
        - [ setProjectService, [ '@app.project' ] ]
        - [ setEventDao, [ '@app.event_dao' ] ]
   
  app.graph:
    class: Mylen\EventFlowAnalyser\Service\GraphVizService
    arguments: ['@logger']
    scope: container
    calls:
        - [ setCommand, [ '%app.graph.command%' ] ]


  app.project:
    class: Mylen\EventFlowAnalyser\Service\ProjectService
    arguments: ['@logger']
    scope: container
    calls:
        - [ setParserService, [ '@app.parser' ] ]
        - [ setFileUploaderService, [ '@mylen.file_uploader' ] ]
        - [ setProjectDao, [ '@app.project_dao' ] ]
        - [ setGraphService, [ '@app.graph' ] ]
        - [ setUserManager, [ '@fos_user.user_manager' ] ]
        
        