parameters:
  file_uploader.file_base_path: "%kernel.root_dir%/../web/uploads"
  file_uploader.web_base_path: "/uploads"
  file_uploader.allowed_extensions:
    # Mime types are just for documentation's sake. 
    # BlueImp filters by supplied extension. No checking of the
    # actual file contents is done. If your mime types are 
    # configured correctly in Apache the browser will have the
    # correct expectations for each file
    - zip #archive
    - xml #text/xml

  # Folder where originals are uploaded. This is the only folder populated for
  # uploads that are not images
  file_uploader.originals:
      folder: originals

  file_uploader.sizes:

services:
    punk_ave.file_uploader:
        class: Mylen\JQueryFileUploadBundle\Services\FileUploader
        arguments: ['%file_uploader.file_base_path%','%file_uploader.web_base_path%','@request','@punk_ave.file_uploader_file_manager','%file_uploader.allowed_extensions%','%file_uploader.sizes%', '%file_uploader.originals%']
        scope: request

    # You usually won't need this sub-service directly,
    # however you can access it from a command, which is
    # convenient if you need to delete files relating to
    # something in a command context
    punk_ave.file_uploader_file_manager:
        class: Mylen\JQueryFileUploadBundle\Services\FileManager
        # class: Mylen\JQueryFileUploadBundle\Services\FileManager
        arguments:
          # For bc reasons we're not changing the names of the parameters
          - file_base_path: '%file_uploader.file_base_path%'
