services:
    ucs_event_flow_analyser.example.navbar:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            # first argument: a named array of menues:
            - { leftmenu: @ucs_event_flow_analyser.examplemenu= }
            # second argument: a named array of FormType Classes
            - { } #searchform: Mopa\Bundle\BootstrapSandboxBundle\Form\Type\ExampleSearchFormType }
            # third argument: a named array of options
            - { title: "AWFM - UCS Event Flow Analyser", titleRoute: "default", fixedTop: true, isFluid: false }
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }

    ucs_event_flow_analyser.example.navbarssubnavbar:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            # first argument: a named array of menues:
            - { menu: @ucs_event_flow_analyser.examplenavbarsubnavmenu= }
            - {}
            # third argument: a named array of options
            - { fixedTop: true, isFluid: true, template: MopaBootstrapBundle:Navbar:subnavbar.html.twig }
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: ucs_event_flow_analyserNavbarsSubNavbar }

    ucs_event_flow_analyser.example.componentssubnavbar:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            # first argument: a named array of menues:
            - { menu: @ucs_event_flow_analyser.examplecomponentssubnavmenu= }
            - {}
            # third argument: a named array of options
            - { fixedTop: true, isFluid: true, template: MopaBootstrapBundle:Navbar:subnavbar.html.twig }
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: ucs_event_flow_analyserComponentsSubNavbar }
